### ISSUE TITLE
Document .env vars

### ISSUE THREAD

**Issue by wdennis** [thediymaker/slurm-node-dashboard#55]
Interesting project, going to give it a test here... Doing the setup now, but not sure what all needs to be filled out for values in the .env file - I'm sure some can be left blank, but others may need to be filled. Would be good to document these, and give examples, either as comments in the included .env.production file, or in the README for the project that references this file.

Also - does the .env file need to be specified in the `pm2` command line as referenced in this doc: https://philna.sh/blog/2023/09/05/nodejs-supports-dotenv/
Or, does the program automatically pick up on it?

**Comment by thediymaker** [comment]
Thanks for bringing this up, I will add a more details on which items are required, and which ones are optional.

**Comment by thediymaker** [comment]
The env file is picked up automatically, so you should not need to specify it in the pm2 command. I went ahead and updated the README with more details about which variables are required, and which ones are optional.
