### ISSUE TITLE
'next build' fails with error about (I think) InfluxDB

### ISSUE THREAD

**Issue by wdennis** [thediymaker/slurm-node-dashboard#56]
Tried to start the app with the .env file I have, and got an error that I should run 'next build'.

So, in trying to do that, I'm getting this error:

```
root@test-slurm-pc:/opt/slurm-node-dashboard# next build
  ▲ Next.js 14.2.5
  - Environments: .env

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
   Collecting page data  ...Error: Unsupported protocol "null in URL: ""
    at new ep (/opt/slurm-node-dashboard/.next/server/app/api/influxdb/route.js:4:2693)
    at new ew (/opt/slurm-node-dashboard/.next/server/app/api/influxdb/route.js:4:9114)
    at 22051 (/opt/slurm-node-dashboard/.next/server/app/api/influxdb/route.js:4:9506)
    at t (/opt/slurm-node-dashboard/.next/server/webpack-runtime.js:1:143)
    at r (/opt/slurm-node-dashboard/.next/server/app/api/influxdb/route.js:4:10544)
    at /opt/slurm-node-dashboard/.next/server/app/api/influxdb/route.js:4:10575
    at t.X (/opt/slurm-node-dashboard/.next/server/webpack-runtime.js:1:1285)
    at /opt/slurm-node-dashboard/.next/server/app/api/influxdb/route.js:4:10557
    at Object.<anonymous> (/opt/slurm-node-dashboard/.next/server/app/api/influxdb/route.js:4:10603)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)

> Build error occurred
Error: Failed to collect page data for /api/influxdb
    at /opt/slurm-node-dashboard/node_modules/next/dist/build/utils.js:1268:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
   Collecting page data  .
```
The empty vars in .env are as so right now:
```
root@test-slurm-pc:/opt/slurm-node-dashboard# grep '=""' .env
URL=""
NEXT_PUBLIC_APP_URL=""
NEXT_PUBLIC_CLUSTER_NAME=""
PROMETHEUS_URL=""
INFLUX_TOKEN=""
INFLUX_URL=""
INFLUX_ORG=""
OPENAI_API_KEY=""
```
Seeing as the errors of "next build" reference InfluxDB (which I thought was optional), can you tell me based on the above where my error is coming from?

(New to all things NodeJS, so please be explicit in what I should look at/do, thanks!)

**Comment by thediymaker** [comment]
I would suggest removing all the Influx* variables from the env file. Currently, InfluxDB is not being used for anything; I initially included it as an example. On systems where InfluxDB is not used, I haven't even specified those variables. I'll implement better tests/checks (or possibly just remove it from the production branch, since it's only being used for testing at the moment. I had planned to use InfluxDB for more tasks, but so far, I've been able to rely on Prometheus for most of the data I originally thought I would be pulling with InfluxDB.

**Comment by thediymaker** [comment]
I did verify that completely removing those env variables allows the build to complete. I also updated the README to make it a little more clear on which vars are needed. Let me know if that is working for you now.

**Comment by wdennis** [comment]
Interesting (in a bad way) - I removed al the INFLUX_* vars out of .env, and did another `next build`, and -- I get the same error!

The error that says: Error: Unsupported protocol "null in URL: ""
Is that due to a blank ("") URL var?

**Comment by wdennis** [comment]
Also removed the URL var (i.e I only have the remaining vars left in the new `.env.production` that you recently updated), but still getting the same error on `next build`... Is there something that should be cleaned before a new build?

**Comment by wdennis** [comment]
OK, I saw you had updated a bunch of code in the project, so I did a git pull, and thereafter a `next build`, and only got one error as so:
```
> Build error occurred
Error: Failed to collect page data for /api/prometheus
    at /opt/slurm-node-dashboard/node_modules/next/dist/build/utils.js:1268:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
   Collecting page data  .
```
So, I took the "PROMETHEUS_URL=" var out, and on another `next build` , it did build correctly:
```
root@test-slurm-pc:/opt/slurm-node-dashboard# next build
  ▲ Next.js 14.2.5
  - Environments: .env

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
 ✓ Generating static pages (13/13)
 ✓ Collecting build traces
 ✓ Finalizing page optimization

Route (app)                              Size     First Load JS
┌ ○ /                                    51.1 kB         322 kB
├ ○ /_not-found                          138 B          87.5 kB
├ ƒ /api/prometheus                      0 B                0 B
├ ƒ /api/rewind                          0 B                0 B
├ ○ /api/slurm/diag                      0 B                0 B
├ ƒ /api/slurm/job/[...id]               0 B                0 B
├ ƒ /api/slurm/job/completed/[...id]     0 B                0 B
├ ○ /api/slurm/jobs                      0 B                0 B
├ ƒ /api/slurm/jobs/node/[...id]         0 B                0 B
├ ƒ /api/slurm/jobs/user/[...id]         0 B                0 B
├ ○ /api/slurm/nodes                     0 B                0 B
├ ƒ /api/slurm/nodes/state/[...id]       0 B                0 B
├ ○ /api/slurm/reservations              0 B                0 B
├ ○ /modules                             2.38 kB         145 kB
└ ○ /rewind                              20.5 kB         286 kB
+ First Load JS shared by all            87.3 kB
  ├ chunks/23-28d1a800708298c8.js        31.7 kB
  ├ chunks/fd9d1056-d0901ed15d41f6fc.js  53.6 kB
  └ other shared chunks (total)          2.01 kB


○  (Static)   prerendered as static content
ƒ  (Dynamic)  server-rendered on demand
```
So, does the PROMETHEUS_URL need to be taken out of .env if not used, or should a null var value be acceptible?

**Comment by thediymaker** [comment]
I updated this to allow the prometheus URL to now be blank, let me know if its still giving you any trouble. I did also remove the influx example, since its not being used. I'm working on creating a documentation site, and will put more examples there as I create them, even if they are not used in the base dashboard.
