### ISSUE TITLE
Getting a client-side exception

### ISSUE THREAD

**Issue by wdennis** [thediymaker/slurm-node-dashboard#60]
In the browser (most recent releases of both Google Chrome and MSFT Edge), the UI begins to render, but then I get "Application error: a client-side exception has occurred (see the browser console for more information)." The error is:
```
23-28d1a800708298c8.js:1 TypeError: Cannot read properties of undefined (reading 'number')
    at eA (page-90128ef509950acb.js:1:47901)
    at rE (fd9d1056-d0901ed15d41f6fc.js:1:40343)
    at l$ (fd9d1056-d0901ed15d41f6fc.js:1:59318)
    at iZ (fd9d1056-d0901ed15d41f6fc.js:1:117925)
    at ia (fd9d1056-d0901ed15d41f6fc.js:1:95164)
    at fd9d1056-d0901ed15d41f6fc.js:1:94986
    at il (fd9d1056-d0901ed15d41f6fc.js:1:94993)
    at nb (fd9d1056-d0901ed15d41f6fc.js:1:26774)
    at nw (fd9d1056-d0901ed15d41f6fc.js:1:27573)
    at fd9d1056-d0901ed15d41f6fc.js:1:28607
window.console.error @ 23-28d1a800708298c8.js:1
l_ @ fd9d1056-d0901ed15d41f6fc.js:1
n.callback @ fd9d1056-d0901ed15d41f6fc.js:1
nB @ fd9d1056-d0901ed15d41f6fc.js:1
nV @ fd9d1056-d0901ed15d41f6fc.js:1
aq @ fd9d1056-d0901ed15d41f6fc.js:1
aY @ fd9d1056-d0901ed15d41f6fc.js:1
a9 @ fd9d1056-d0901ed15d41f6fc.js:1
aY @ fd9d1056-d0901ed15d41f6fc.js:1
a9 @ fd9d1056-d0901ed15d41f6fc.js:1
aY @ fd9d1056-d0901ed15d41f6fc.js:1
a9 @ fd9d1056-d0901ed15d41f6fc.js:1
aY @ fd9d1056-d0901ed15d41f6fc.js:1
a9 @ fd9d1056-d0901ed15d41f6fc.js:1
aY @ fd9d1056-d0901ed15d41f6fc.js:1
a9 @ fd9d1056-d0901ed15d41f6fc.js:1
aY @ fd9d1056-d0901ed15d41f6fc.js:1
a9 @ fd9d1056-d0901ed15d41f6fc.js:1
aY @ fd9d1056-d0901ed15d41f6fc.js:1
a9 @ fd9d1056-d0901ed15d41f6fc.js:1
aY @ fd9d1056-d0901ed15d41f6fc.js:1
a9 @ fd9d1056-d0901ed15d41f6fc.js:1
aY @ fd9d1056-d0901ed15d41f6fc.js:1
(anonymous) @ fd9d1056-d0901ed15d41f6fc.js:1
is @ fd9d1056-d0901ed15d41f6fc.js:1
nb @ fd9d1056-d0901ed15d41f6fc.js:1
nw @ fd9d1056-d0901ed15d41f6fc.js:1
(anonymous) @ fd9d1056-d0901ed15d41f6fc.js:1
```

**Comment by wdennis** [comment]
Added the PROMETHEUS_URL back into .env (spec'd value as `PROMETHEUS_URL="127.0.0.1:9090"` - IP shouldn't matter, right?), stopped the app, recompiled via `next build` (was that needful? Do I even need to run `next build` if I change .env params?), and started the app, but still getting the same error:
```
23-28d1a800708298c8.js:1 TypeError: Cannot read properties of undefined (reading 'number')
    at eA (page-90128ef509950acb.js:1:47901)
    at rE (fd9d1056-d0901ed15d41f6fc.js:1:40343)
    at l$ (fd9d1056-d0901ed15d41f6fc.js:1:59318)
    at iZ (fd9d1056-d0901ed15d41f6fc.js:1:117925)
    at ia (fd9d1056-d0901ed15d41f6fc.js:1:95164)
    at fd9d1056-d0901ed15d41f6fc.js:1:94986
    at il (fd9d1056-d0901ed15d41f6fc.js:1:94993)
    at nb (fd9d1056-d0901ed15d41f6fc.js:1:26774)
    at nw (fd9d1056-d0901ed15d41f6fc.js:1:27573)
    at fd9d1056-d0901ed15d41f6fc.js:1:28607
```

**Comment by thediymaker** [comment]
you might try deleting the .next folder, this is the cache from the previous builds. Also another thing to try is instead of running "npm run build", run "npm run dev". If this works it likely has something to do with build, generating the static pages.

**Comment by thediymaker** [comment]
Ok, I have been able to reproduce this error, by providing an incorrect API key for slurm. what version of slurm are you using?  can you verify the key is valid using something like insomnia or postman?

**Comment by wdennis** [comment]
This is against Slurm 23.11.7

I will check query with my API key and let you know.

**Comment by wdennis** [comment]
OK, did indeed have a REST query issue (SlurmDBD was not running JWT auth), that's fixed now, and now the dashboard is working :) 

If I try commenting out the Prom URL envvar, do I have to rebuild?

**Comment by thediymaker** [comment]
That is great to hear! I think right now it will require something in the field, I'm going to make some updates tonight for error checking on the Slurm API key, and then update the prometheus env to allow an empty string. Thanks again for testing this! I hope it is useful for you! Please feel free to open enhancement issues as well, anything that you think might be useful and i'll see about adding something in.
