### ISSUE TITLE
node memory abbreviating

### ISSUE THREAD

**Issue by asu-wdizon** [thediymaker/slurm-node-dashboard#9]
is it possible to reduce precision on the "MEM: 10240 / 192000" to perhaps list by GB?

So it might instead show "MEM: 10 / 192".

This should help reduce overall noise since we likely will not be acting on the increased precision. Additionally, this will ensure that MEM's value is always on a single line, which gives an opportunity to put new info on there, e.g., Load Average, etc.

**Comment by jlee562** [comment]
Complete!
